-- Allow explicit id values on skills so dev-to-prod sync can preserve IDs.
-- GENERATED ALWAYS rejects explicit inserts; BY DEFAULT allows them.
ALTER TABLE public.skills ALTER COLUMN id SET GENERATED BY DEFAULT;
